### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by mariusrak** [arangodb/graphql-sync#1]
So how to use this? Do I use it with foxx? Or with nodejs and connecting to ArangoDB server? Some tutorial would be helpful and appreciated.

**Comment by pluma** [comment]
Hi @mariusrak and thank you for your interest.

This library just provides a fork of the outer most layer of GraphQL that removes the `Promise` related logic from the library's external API to allow using it in synchronous environments like ArangoDB. You can use it exactly as you would use the official `graphql` module for Node and the browser.

For an example of using it in Foxx see our example service: https://github.com/arangodb-foxx/demo-graphql (also available from the Foxx store in the web interface). Keep in mind that graphql-sync only works with ArangoDB 2.8 (or newer) due to some incompatibilities with Node-style module resolution in previous versions.
