### ISSUE TITLE
User-supplied graphql

### ISSUE THREAD

**Issue by dustinfarris** [arangodb/graphql-sync#5]
First of all, thanks for making this.  I've been beating my head against the promise that graphql returns for a while now until I stumbled across this repo.

I'm a bit of a noob when it comes to dependency resolution in node, but would it be preferable for the user to deliberately bring in their own graphql in their own project's package.json, and just specify it here as a peerDependency?

In the README, the examples show building a schema using graphql-sync as a proxy to grab the various modules needed.  It seems to me that a user might want to reference the actual graphql package for this generally, and only use graphql-sync for the graphql function itself.

**Comment by pluma** [comment]
Since graphql-sync tracks the matching graphql-js versions specifically (i.e. graphql-sync@0.5.0-sync uses graphql@0.5) you'd just need to make sure you're using the matching version of graphql-js when using graphql-sync. As graphql-js is currently on major version zero, all changes in the minor version should be considered breaking (like major version changes post-1.0), IOW you will probably want to use graphql-sync@0.5.0-sync with graphql@0.5 as graphql@0.6 might be backwards-incompatible and break something.

The reason the examples are using graphql-sync for everything is that the module was written specifically for non-async environments like ArangoDB where the regular graphql-js module doesn't work. In this scenario user code shouldn't be dealing with graphql-js directly and it's more comfortable to have graphql-sync as a drop-in replacement.

That said, I realise graphql-js has seen several minor version releases since 0.5, so I'll make sure to port those to graphql-sync soon but probably no earlier than next week.

**Comment by pluma** [comment]
As of ArangoDB 3.2 it will be possible to provide your own copy of graphql-sync from your Foxx service when using the GraphQL router. This should allow ArangoDB to avoid breaking changes between minor releases without locking users into outdated versions of GraphQL.

However we still need to update graphql-sync to the latest versions of graphql-js.
